# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.key_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.key_txt.setGeometry(QtCore.QRect(70, 140, 591, 31))
        self.key_txt.setObjectName("key_txt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(460, 280, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.ciphertext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ciphertext_txt.setGeometry(QtCore.QRect(70, 190, 591, 71))
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 171, 41))
        self.label.setObjectName("label")
        self.plaintext_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintext_txt.setGeometry(QtCore.QRect(70, 50, 591, 71))
        self.plaintext_txt.setObjectName("plaintext_txt")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 51, 20))
        self.label_4.setObjectName("label_4")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(130, 280, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        # Thêm label hiển thị tên
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 310, 250, 20))
        self.label_name.setObjectName("label_name")

        # Thêm label hiển thị MSSV/ĐCKH
        self.label_mssv = QtWidgets.QLabel(self.centralwidget)
        self.label_mssv.setGeometry(QtCore.QRect(20, 330, 250, 20))
        self.label_mssv.setObjectName("label_mssv")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Key:"))
        self.label_2.setText(_translate("MainWindow", "Plaintext:"))
        self.btn_decrypt.setText(_translate("MainWindow", "decrypt"))
        self.label.setText(_translate("MainWindow", "Vigenere Cipher"))
        self.label_4.setText(_translate("MainWindow", "Ciphertext:"))
        self.btn_encrypt.setText(_translate("MainWindow", "encrypt"))
        self.label_name.setText(_translate("MainWindow", "Tên: Nguyễn Nguyên Thắng"))
        self.label_mssv.setText(_translate("MainWindow", "MSSV: 2380605509"))
